    -- Acura
    ['tltypes'] = {
        ['name'] = 'TL Type-S',
        ['brand'] = 'Acura',
        ['model'] = 'tltypes',
        ['price'] = 53700,
        ['category'] = 'acura',
        ['categoryLabel'] = 'Acura',
        ['hash'] = `tltypes`,
        ['shop'] = 'pdm',
    },
    -- Aston Martin
    ['amdbx'] = {
        ['name'] = 'DBX Carbon Edition',
        ['brand'] = 'Aston Martin',
        ['model'] = 'amdbx',
        ['price'] = 188986,
        ['category'] = 'am',
        ['categoryLabel'] = 'Aston Martin',
        ['hash'] = `amdbx`,
        ['shop'] = 'luxury',
    },
    ['ast'] = {
        ['name'] = '2013 Vanquish',
        ['brand'] = 'Aston Martin',
        ['model'] = 'ast',
        ['price'] = 229950,
        ['category'] = 'am',
        ['categoryLabel'] = 'Aston Martin',
        ['hash'] = `ast`,
        ['shop'] = 'luxury',
    },
    -- Audi
    ['80B4'] = {
        ['name'] = '1995 Cabriolet (RS2) (B4)',
        ['brand'] = 'Audi',
        ['model'] = '80B4',
        ['price'] = 35000,
        ['category'] = 'audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = '80B4',
        ['shop'] = 'pdm',
    },
    ['audquattros'] = {
        ['name'] = '1983 Quattro Sport',
        ['brand'] = 'Audi',
        ['model'] = 'audquattros',
        ['price'] = 65000,
        ['category'] = 'audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = 'audquattros',
        ['shop'] = 'pdm',
    },
    ['aaq4'] = {
        ['name'] = '2017 A4 Quattro ABT',
        ['brand'] = 'Audi',
        ['model'] = 'aaq4',
        ['price'] = 15000,
        ['category'] = 'audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = 'aaq4',
        ['shop'] = 'pdm',
    },
    ['q820'] = {
        ['name'] = '2020 Q8 50TDI',
        ['brand'] = 'Audi',
        ['model'] = 'q820',
        ['price'] = 57500,
        ['category'] = 'audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = 'q820',
        ['shop'] = 'pdm',
    },
    ['r8ppi'] = {
        ['name'] = '2013 R8 V10',
        ['brand'] = 'Audi',
        ['model'] = 'r8ppi',
        ['price'] = 45000,
        ['category'] = 'audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = 'r8ppi',
        ['shop'] = 'pdm',
    },
    ['r820'] = {
        ['name'] = '2020 R8',
        ['brand'] = 'Audi',
        ['model'] = 'r820',
        ['price'] = 90000,
        ['category'] = 'audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = 'r820',
        ['shop'] = 'pdm',
    },
    ['rs6'] = {
        ['name'] = '2016 RS6 C7',
        ['brand'] = 'Audi',
        ['model'] = 'rs6',
        ['price'] = 75005,
        ['category'] = 'audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = 'rs6',
        ['shop'] = 'pdm',
    },
    ['rs72020'] = {
        ['name'] = '2020 RS7',
        ['brand'] = 'Audi',
        ['model'] = 'rs72020',
        ['price'] = 85500,
        ['category'] = 'audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = 'rs72020',
        ['shop'] = 'pdm',
    },
    ['s8d2'] = {
        ['name'] = '1998 S8 (D2/PFL)',
        ['brand'] = 'Audi',
        ['model'] = 's8d2',
        ['price'] = 15000,
        ['category'] = 'audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = 's8d2',
        ['shop'] = 'pdm',
    },
    ['sq72016'] = {
        ['name'] = '2016 SQ7',
        ['brand'] = 'Audi',
        ['model'] = 'sq72016',
        ['price'] = 65000,
        ['category'] = 'audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = 'sq72016',
        ['shop'] = 'pdm',
    },
    ['ttrs'] = {
        ['name'] = '2010 TT RS',
        ['brand'] = 'Audi',
        ['model'] = 'ttrs',
        ['price'] = 15000,
        ['category'] = 'audi',
        ['categoryLabel'] = 'Audi',
        ['hash'] = 'ttrs',
        ['shop'] = 'pdm',
    },
    -- Bentley
    ['bbentayga'] = {
        ['name'] = 'Bentley Bentayga',
        ['brand'] = 'Bentley',
        ['model'] = 'bbentayga',
        ['price'] = 150,
        ['category'] = 'bentley',
        ['categoryLabel'] = 'Bentley',
        ['hash'] = 'bbentayga',
        ['shop'] = 'pdm',
    },
    ['cgts'] = {
        ['name'] = '2020 Bentley Continental GT Convertible',
        ['brand'] = 'Bentley',
        ['model'] = 'cgts',
        ['price'] = 150,
        ['category'] = 'bentley',
        ['categoryLabel'] = 'Bentley',
        ['hash'] = 'cgts',
        ['shop'] = 'pdm',
    },
    -- BMW
    ['760li04'] = {
        ['name'] = '2004 BMW 760Li Individual (E66/PFL)',
        ['brand'] = 'BMW',
        ['model'] = '760li04',
        ['price'] = 45980,
        ['category'] = 'bmw',
        ['categoryLabel'] = 'BMW',
        ['hash'] = '760li04',
        ['shop'] = 'pdm',
    },
    ['e34'] = {
        ['name'] = '1995 BMW M5 E34',
        ['brand'] = 'BMW',
        ['model'] = 'e34',
        ['price'] = 31500,
        ['category'] = 'bmw',
        ['categoryLabel'] = 'BMW',
        ['hash'] = 'e34',
        ['shop'] = 'pdm',
    },
    ['m2'] = {
        ['name'] = '2016 BMW M2',
        ['brand'] = 'BMW',
        ['model'] = 'm2',
        ['price'] = 55000,
        ['category'] = 'bmw',
        ['categoryLabel'] = 'BMW',
        ['hash'] = 'm2',
        ['shop'] = 'pdm',
    },
    ['m3e36'] = {
        ['name'] = '1997 BMW M3 E36',
        ['brand'] = 'BMW',
        ['model'] = 'm3e36',
        ['price'] = 35000,
        ['category'] = 'bmw',
        ['categoryLabel'] = 'BMW',
        ['hash'] = 'm3e36',
        ['shop'] = 'pdm',
    },
    ['m3e92'] = {
        ['name'] = '2008 BMW M3 e92',
        ['brand'] = 'BMW',
        ['model'] = 'm3e92',
        ['price'] = 3500,
        ['category'] = 'bmw',
        ['categoryLabel'] = 'BMW',
        ['hash'] = 'm3e92',
        ['shop'] = 'pdm',
    },
    ['m3f80'] = {
        ['name'] = '2015 BMW M3 (F80)',
        ['brand'] = 'BMW',
        ['model'] = 'm3f80',
        ['price'] = 42000,
        ['category'] = 'bmw',
        ['categoryLabel'] = 'BMW',
        ['hash'] = 'm3f80',
        ['shop'] = 'pdm',
    },
    ['m4f82'] = {
        ['name'] = '2015 BMW M4 F82',
        ['brand'] = 'BMW',
        ['model'] = 'm4f82',
        ['price'] = 58000,
        ['category'] = 'bmw',
        ['categoryLabel'] = 'BMW',
        ['hash'] = 'm4f82',
        ['shop'] = 'pdm',
    },
    ['m6f13'] = {
        ['name'] = 'BMW M6 F13 Shadow Line',
        ['brand'] = 'BMW',
        ['model'] = 'm6f13',
        ['price'] = 87000,
        ['category'] = 'bmw',
        ['categoryLabel'] = 'BMW',
        ['hash'] = 'm6f13',
        ['shop'] = 'pdm',
    },
    ['z419'] = {
        ['name'] = '2019 BMW Z4 M40i',
        ['brand'] = 'BMW',
        ['model'] = 'z419',
        ['price'] = 56600,
        ['category'] = 'bmw',
        ['categoryLabel'] = 'BMW',
        ['hash'] = 'z419',
        ['shop'] = 'pdm',
    },
    -- Bugatti
    ['bolide'] = {
        ['name'] = '2020 Bugatti Bolide',
        ['brand'] = 'Bugatti',
        ['model'] = 'bolide',
        ['price'] = 566000,
        ['category'] = 'bugatti',
        ['categoryLabel'] = 'Bugatti',
        ['hash'] = 'z4bolide19',
        ['shop'] = 'luxury',
    },
    -- Cadillac
    ['cats'] = {
        ['name'] = '2016 Cadillac ATS-V Coupe',
        ['brand'] = 'Cadillac',
        ['model'] = 'cats',
        ['price'] = 65000,
        ['category'] = 'cadillac',
        ['categoryLabel'] = 'Cadillac',
        ['hash'] = 'cats',
        ['shop'] = 'pdm',
    },
    ['cesc21'] = {
        ['name'] = '2021 Cadillac Escalade',
        ['brand'] = 'Cadillac',
        ['model'] = 'cesc21',
        ['price'] = 155000,
        ['category'] = 'cadillac',
        ['categoryLabel'] = 'Cadillac',
        ['hash'] = 'cesc21',
        ['shop'] = 'pdm',
    },
    -- Chevrolet
    ['09tahoe'] = {
        ['name'] = '2009 Chevrolet Tahoe',
        ['brand'] = 'Chevrolet',
        ['model'] = '09tahoe',
        ['price'] = 9500,
        ['category'] = 'chevrolet',
        ['categoryLabel'] = 'Chevrolet',
        ['hash'] = '09tahoe',
        ['shop'] = 'pdm',
    },
    ['15tahoe'] = {
        ['name'] = '2015 Chevrolet Tahoe',
        ['brand'] = 'Chevrolet',
        ['model'] = '15tahoe',
        ['price'] = 25000,
        ['category'] = 'chevrolet',
        ['categoryLabel'] = 'Chevrolet',
        ['hash'] = '15tahoe',
        ['shop'] = 'pdm',
    },
    ['2020ss'] = {
        ['name'] = '2020 Chevrolet Camaro SS',
        ['brand'] = 'Chevrolet',
        ['model'] = '2020ss',
        ['price'] = 95870,
        ['category'] = 'chevrolet',
        ['categoryLabel'] = 'Chevrolet',
        ['hash'] = '2020ss',
        ['shop'] = 'pdm',
    },
    ['camrs17'] = {
        ['name'] = '2017 Chevrolet Camaro RS',
        ['brand'] = 'Chevrolet',
        ['model'] = 'camrs17',
        ['price'] = 75000,
        ['category'] = 'chevrolet',
        ['categoryLabel'] = 'Chevrolet',
        ['hash'] = 'camrs17',
        ['shop'] = 'pdm',
    },
    ['tahoe21'] = {
        ['name'] = '2021 Chevrolet Tahoe RST',
        ['brand'] = 'Chevrolet',
        ['model'] = 'tahoe21',
        ['price'] = 155700,
        ['category'] = 'chevrolet',
        ['categoryLabel'] = 'Chevrolet',
        ['hash'] = 'tahoe21',
        ['shop'] = 'pdm',
    },
    ['corvettec5z06'] = {
        ['name'] = 'Chevrolet Corvette C5 Z06',
        ['brand'] = 'Chevrolet',
        ['model'] = 'corvettec5z06',
        ['price'] = 1000000,
        ['category'] = 'chevrolet',
        ['categoryLabel'] = 'Chevrolet',
        ['hash'] = 'corvettec5z06',
        ['shop'] = 'pdm',
    },
    ['czr1'] = {
        ['name'] = '2009 Chevrolet Corvette ZR1',
        ['brand'] = 'Chevrolet',
        ['model'] = 'czr1',
        ['price'] = 1000000,
        ['category'] = 'chevrolet',
        ['categoryLabel'] = 'Chevrolet',
        ['hash'] = 'czr1',
        ['shop'] = 'pdm',
    },
    ['c7'] = {
        ['name'] = '2014 Chevrolet Corvette C7 Stingray',
        ['brand'] = 'Chevrolet',
        ['model'] = 'c7',
        ['price'] = 1000000,
        ['category'] = 'chevrolet',
        ['categoryLabel'] = 'Chevrolet',
        ['hash'] = 'c7',
        ['shop'] = 'pdm',
    },
    ['stingray'] = {
        ['name'] = '2020 Chevrolet Corvette C8 Stingray',
        ['brand'] = 'Chevrolet',
        ['model'] = 'stingray',
        ['price'] = 1000000,
        ['category'] = 'chevrolet',
        ['categoryLabel'] = 'Chevrolet',
        ['hash'] = 'stingray',
        ['shop'] = 'pdm',
    },
    ['16charger'] = {
        ['name'] = '2016 Dodge Charger',
        ['brand'] = 'Dodge',
        ['model'] = '16charger',
        ['price'] = 75000,
        ['category'] = 'dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = '16charger',
        ['shop'] = 'pdm',
    },    
    ['99viper'] = {
        ['name'] = '1999 Dodge Viper GTS ACR',
        ['brand'] = 'Dodge',
        ['model'] = '99viper',
        ['price'] = 75000,
        ['category'] = 'dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = '99viper',
        ['shop'] = 'pdm',
    },
    ['chr20'] = {
        ['name'] = 'Dodge Charger Hellcat Widebody 2021',
        ['brand'] = 'Dodge',
        ['model'] = 'chr20',
        ['price'] = 75000,
        ['category'] = 'dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = 'chr20',
        ['shop'] = 'pdm',
    },    
    ['demon'] = {
        ['name'] = '2018 Dodge Challenger SRT Demon',
        ['brand'] = 'Dodge',
        ['model'] = 'demon',
        ['price'] = 75000,
        ['category'] = 'dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = 'demon',
        ['shop'] = 'pdm',
    },    
    ['raid'] = {
        ['name'] = 'Dodge Challenger Raid',
        ['brand'] = 'Dodge',
        ['model'] = 'raid',
        ['price'] = 75000,
        ['category'] = 'dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = 'raid',
        ['shop'] = 'pdm',
    },    
    ['ram2500'] = {
        ['name'] = '2015 Dodge RAM 2500',
        ['brand'] = 'Dodge',
        ['model'] = 'ram2500',
        ['price'] = 75000,
        ['category'] = 'dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = 'ram2500',
        ['shop'] = 'pdm',
    },
    ['srt4'] = {
        ['name'] = 'Dodge Neon SRT-4',
        ['brand'] = 'Dodge',
        ['model'] = 'srt4',
        ['price'] = 75000,
        ['category'] = 'dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = 'srt4',
        ['shop'] = 'pdm',
    },
    ['trx'] = {
        ['name'] = '1500 TRX',
        ['brand'] = 'RAM',
        ['model'] = 'trx',
        ['price'] = 59000,
        ['category'] = 'dodge',
        ['categoryLabel'] = 'Dodge',
        ['hash'] = `trx`,
        ['shop'] = 'pdm',
    },
    ['16challenger'] = {
        ['name'] = '2016 Dodge Charger',
        ['brand'] = 'Dodge',
        ['model'] = '16challenger',
        ['price'] = 59000,
        ['category'] = 'custom',
        ['categoryLabel'] = 'Custom',
        ['hash'] = `16challenger`,
        ['shop'] = 'pdm',
    },
    -- Ferrari
    ['488'] = {
        ['name'] = 'Ferrari 488 Spider',
        ['brand'] = 'Ferrari',
        ['model'] = '488',
        ['price'] = 331000,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = '488',
        ['shop'] = 'luxury',
    },
    ['f430s'] = {
        ['name'] = 'Ferrari F430 Scuderia',
        ['brand'] = 'Ferrari',
        ['model'] = 'f430s',
        ['price'] = 479900,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = 'f430s',
        ['shop'] = 'luxury',
    },
    ['f812'] = {
        ['name'] = '2018 Ferrari 812 Superfast',
        ['brand'] = 'Ferrari',
        ['model'] = 'f812',
        ['price'] = 433765,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = 'f812',
        ['shop'] = 'luxury',
    },
    ['fct'] = {
        ['name'] = '2015 Ferrari California T',
        ['brand'] = 'Ferrari',
        ['model'] = 'fct',
        ['price'] = 222170,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = 'fct',
        ['shop'] = 'luxury',
    },
    ['fxxk'] = {
        ['name'] = 'Ferrari FXX-K Hybrid Hypercar',
        ['brand'] = 'Ferrari',
        ['model'] = 'fxxk',
        ['price'] = 2656000,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = 'fxxk',
        ['shop'] = 'luxury',
    },
    ['laferrari'] = {
        ['name'] = '2015 Ferrari LaFerrari',
        ['brand'] = 'Ferrari',
        ['model'] = 'laferrari',
        ['price'] = 5500000,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = 'laferrari',
        ['shop'] = 'luxury',
    },    
    ['mig'] = {
        ['name'] = 'Ferrari Enzo',
        ['brand'] = 'Ferrari',
        ['model'] = 'mig',
        ['price'] = 3133937,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = 'mig',
        ['shop'] = 'luxury',
    },
    ['yFe458i1'] = {
        ['name'] = '458 Italia',
        ['brand'] = 'Ferrari',
        ['model'] = 'yFe458i1',
        ['price'] = 325000,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = 'yFe458i1',
        ['shop'] = 'luxury',
    },
    ['yFe458i2'] = {
        ['name'] = '458 Speciale',
        ['brand'] = 'Ferrari',
        ['model'] = 'yFe458i2',
        ['price'] = 401000,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = 'yFe458i2',
        ['shop'] = 'luxury',
    },
    ['yFe458s1'] = {
        ['name'] = '458 Spider',
        ['brand'] = 'Ferrari',
        ['model'] = 'yFe458s1',
        ['price'] = 453420,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = 'yFe458s1',
        ['shop'] = 'luxury',
    },
    ['yFe458s2'] = {
        ['name'] = '458 Speciale Aperta',
        ['brand'] = 'Ferrari',
        ['model'] = 'yFe458s2',
        ['price'] = 458420,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = 'yFe458s2',
        ['shop'] = 'luxury',
    },
    ['yFeF12A'] = {
        ['name'] = 'Ferrari F60 America',
        ['brand'] = 'Ferrari',
        ['model'] = 'yFeF12A',
        ['price'] = 2500000,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = 'yFeF12A',
        ['shop'] = 'luxury',
    },
    ['yFeF12T'] = {
        ['name'] = 'Ferrari F12 TRS Roadster',
        ['brand'] = 'Ferrari',
        ['model'] = 'yFeF12T',
        ['price'] = 4200000,
        ['category'] = 'ferrari',
        ['categoryLabel'] = 'Ferrari',
        ['hash'] = 'yFeF12T',
        ['shop'] = 'luxury',
    },
    -- Ford
    ['f15078'] = {
        ['name'] = '1978 Ford F150 XLT Ranger',
        ['brand'] = 'Ford',
        ['model'] = 'f15078',
        ['price'] = 21300,
        ['category'] = 'ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = 'f15078',
        ['shop'] = 'pdm',
    },
    ['f150'] = {
        ['name'] = '2012 Ford F150 SVT Raptor R',
        ['brand'] = 'Ford',
        ['model'] = 'f150',
        ['price'] = 17762,
        ['category'] = 'ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = 'f150',
        ['shop'] = 'pdm',
    },
    ['fgt'] = {
        ['name'] = '2005 Ford GT',
        ['brand'] = 'Ford',
        ['model'] = 'fgt',
        ['price'] = 26143,
        ['category'] = 'ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = 'fgt',
        ['shop'] = 'pdm',
    },
    ['gt17'] = {
        ['name'] = '2017 Ford GT',
        ['brand'] = 'Ford',
        ['model'] = 'gt17',
        ['price'] = 453750,
        ['category'] = 'ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = 'gt17',
        ['shop'] = 'pdm',
    },
    ['mustang50th'] = {
        ['name'] = '2015 Ford Mustang GT 50 Years Special Edition',
        ['brand'] = 'Ford',
        ['model'] = 'mustang50th',
        ['price'] = 82500,
        ['category'] = 'ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = 'mustang50th',
        ['shop'] = 'pdm',
    },
    ['raptor2017'] = {
        ['name'] = '2017 Ford Raptor',
        ['brand'] = 'Ford',
        ['model'] = 'raptor2017',
        ['price'] = 23995,
        ['category'] = 'ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = 'raptor2017',
        ['shop'] = 'pdm',
    },
    ['wildtrak'] = {
        ['name'] = '2021 Ford Bronco Wildtrak',
        ['brand'] = 'Ford',
        ['model'] = 'wildtrak',
        ['price'] = 61994,
        ['category'] = 'ford',
        ['categoryLabel'] = 'Ford',
        ['hash'] = 'wildtrak',
        ['shop'] = 'pdm',
    },
    -- Honda   
    ['honcrx91'] = {
        ['name'] = 'Honda CRX SiR 1991',
        ['brand'] = 'Honda',
        ['model'] = 'honcrx91',
        ['price'] = 27287,
        ['category'] = 'honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = 'honcrx91',
        ['shop'] = 'pdm',
    },
    ['na1'] = {
        ['name'] = '1992 Honda NSX-R (NA1)',
        ['brand'] = 'Honda',
        ['model'] = 'na1',
        ['price'] = 69000,
        ['category'] = 'honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = 'na1',
        ['shop'] = 'pdm',
    },
    ['ap2'] = {
        ['name'] = 'Honda S2000 AP2',
        ['brand'] = 'Honda',
        ['model'] = 'ap2',
        ['price'] = 43000,
        ['category'] = 'honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = 'ap2',
        ['shop'] = 'pdm',
    },
    ['dragekcivick'] = {
        ['name'] = '1997 Honda Civic Sedan Drag Version',
        ['brand'] = 'Honda',
        ['model'] = 'dragekcivick',
        ['price'] = 15000,
        ['category'] = 'honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = 'dragekcivick',
        ['shop'] = 'pdm',
    },
    ['fk8'] = {
        ['name'] = '2018 Honda Civic Type-R (FK8)',
        ['brand'] = 'Honda',
        ['model'] = 'fk8',
        ['price'] = 34890,
        ['category'] = 'honda',
        ['categoryLabel'] = 'Honda',
        ['hash'] = 'fk8',
        ['shop'] = 'pdm',
    },
    -- Jaguar 
    ['fpacehm'] = {
        ['name'] = 'Jaguar F-pace 2017 Hamann Edition',
        ['brand'] = 'Jaguar',
        ['model'] = 'fpacehm',
        ['price'] = 34890,
        ['category'] = 'jaguar',
        ['categoryLabel'] = 'Jaguar',
        ['hash'] = 'fpacehm',
        ['shop'] = 'luxury',
    },
    -- Jeep
    ['jeep2012'] = {
        ['name'] = '2012 Jeep Wrangler',
        ['brand'] = 'Jeep',
        ['model'] = 'jeep2012',
        ['price'] = 35650,
        ['category'] = 'jeep',
        ['categoryLabel'] = 'Jeep',
        ['hash'] = 'jeep2012',
        ['shop'] = 'pdm',
    },
    ['jeepreneg'] = {
        ['name'] = 'Jeep Renegade',
        ['brand'] = 'Jeep',
        ['model'] = 'jeepreneg',
        ['price'] = 25607,
        ['category'] = 'jeep',
        ['categoryLabel'] = 'Jeep',
        ['hash'] = 'jeepreneg',
        ['shop'] = 'pdm',
    },
    ['srt8'] = {
        ['name'] = '2015 Jeep SRT-8',
        ['brand'] = 'Jeep',
        ['model'] = 'srt8',
        ['price'] = 39875,
        ['category'] = 'jeep',
        ['categoryLabel'] = 'Jeep',
        ['hash'] = 'srt8',
        ['shop'] = 'pdm',
    },
    ['trhawk'] = {
        ['name'] = '2018 Jeep Grand Cherokee Trackhawk Series IV',
        ['brand'] = 'Jeep',
        ['model'] = 'trhawk',
        ['price'] = 86000,
        ['category'] = 'jeep',
        ['categoryLabel'] = 'Jeep',
        ['hash'] = 'trhawk',
        ['shop'] = 'pdm',
    },
    -- Koenigsegg
    ['agerars'] = {
        ['name'] = '2017 Koenigsegg Agera RS',
        ['brand'] = 'Koenigsegg',
        ['model'] = 'agerars',
        ['price'] = 3000000,
        ['category'] = 'koenigsegg',
        ['categoryLabel'] = 'Koenigsegg',
        ['hash'] = 'agerars',
        ['shop'] = 'luxury',
    },
    ['regera'] = {
        ['name'] = 'Koenigsegg Regera',
        ['brand'] = 'Koenigsegg',
        ['model'] = 'regera',
        ['price'] = 2100000,
        ['category'] = 'koenigsegg',
        ['categoryLabel'] = 'Koenigsegg',
        ['hash'] = 'regera',
        ['shop'] = 'luxury',
    },
	-- LAMBORGHINI
    ['huracanst'] = {
        ['name'] = 'Lamborghini Huracan Super Trofeo',
        ['brand'] = 'Lamborghini',
        ['model'] = 'huracanst',
        ['price'] = 540000,
        ['category'] = 'lamborghini',
        ['categoryLabel'] = 'Lamborghini',
        ['hash'] = 'huracanst',
        ['shop'] = 'luxury',
    },
    ['lambose'] = {
        ['name'] = 'Lamborghini Sesto Elemento',
        ['brand'] = 'Lamborghini',
        ['model'] = 'lambose',
        ['price'] = 2750000,
        ['category'] = 'lamborghini',
        ['categoryLabel'] = 'Lamborghini',
        ['hash'] = 'lambose',
        ['shop'] = 'luxury',
    },
    ['lp670sv'] = {
        ['name'] = '2009 Lamborghini Murcielago LP 670-4 SV',
        ['brand'] = 'Lamborghini',
        ['model'] = 'lp670sv',
        ['price'] = 500000,
        ['category'] = 'lamborghini',
        ['categoryLabel'] = 'Lamborghini',
        ['hash'] = 'lp670sv',
        ['shop'] = 'luxury',
    },
    ['lp700r'] = {
        ['name'] = '2013 Lamborghini Aventador LP700-4 Roadster',
        ['brand'] = 'Lamborghini',
        ['model'] = 'lp700r',
        ['price'] = 450000,
        ['category'] = 'lamborghini',
        ['categoryLabel'] = 'Lamborghini',
        ['hash'] = 'lp700r',
        ['shop'] = 'luxury',
    },
    ['svj63'] = {
        ['name'] = 'Lamborghini Aventador SVJ',
        ['brand'] = 'Lamborghini',
        ['model'] = 'svj63',
        ['price'] = 577000,
        ['category'] = 'lamborghini',
        ['categoryLabel'] = 'Lamborghini',
        ['hash'] = 'svj63',
        ['shop'] = 'luxury',
    },
    ['urus'] = {
        ['name'] = 'Lamborghini Urus',
        ['brand'] = 'Lamborghini',
        ['model'] = 'urus',
        ['price'] = 270311,
        ['category'] = 'lamborghini',
        ['categoryLabel'] = 'Lamborghini',
        ['hash'] = 'urus',
        ['shop'] = 'luxury',
    },
    ['veneno'] = {
        ['name'] = '2013 Lamborghini Veneno LP750-4',
        ['brand'] = 'Lamborghini',
        ['model'] = 'veneno',
        ['price'] = 3500000,
        ['category'] = 'lamborghini',
        ['categoryLabel'] = 'Lamborghini',
        ['hash'] = 'veneno',
        ['shop'] = 'luxury',
    },
	-- LEXUS
    ['gs350'] = {
        ['name'] = 'Lexus GS 350',
        ['brand'] = 'Lexus GS 350',
        ['model'] = 'gs350',
        ['price'] = 52400,
        ['category'] = 'lexus',
        ['categoryLabel'] = 'Lexus',
        ['hash'] = `gs350`,
        ['shop'] = 'pdm',
    },
    ['is350mod'] = {
        ['name'] = '2014 Lexus IS 350',
        ['brand'] = '2014 Lexus IS 350',
        ['model'] = 'is350mod',
        ['price'] = 54650,
        ['category'] = 'lexus',
        ['categoryLabel'] = 'Lexus',
        ['hash'] = `is350mod`,
        ['shop'] = 'pdm',
    },
    ['rcf'] = {
        ['name'] = '2015 Lexus RCF',
        ['brand'] = '2015 Lexus RCF',
        ['model'] = 'rcf',
        ['price'] = 88600,
        ['category'] = 'lexus',
        ['categoryLabel'] = 'Lexus',
        ['hash'] = `rcf`,
        ['shop'] = 'pdm',
    },
    -- LANDROVER
    ['lrrr'] = {
        ['name'] = '1973 Land Rover Range Rover',
        ['brand'] = 'Land Rover',
        ['model'] = 'lrrr',
        ['price'] = 4070,
        ['category'] = 'landrover',
        ['categoryLabel'] = 'Land Rover',
        ['hash'] = `lrrr`,
        ['shop'] = 'pdm',
    },
    -- LOTUS
    ['esprit02'] = {
        ['name'] = '1973 Land Rover Range Rover',
        ['brand'] = 'Land Rover',
        ['model'] = 'esprit02',
        ['price'] = 18785,
        ['category'] = 'lotus',
        ['categoryLabel'] = 'Lotus',
        ['hash'] = `esprit02`,
        ['shop'] = 'luxury',
    },
    -- MASERATI
    ['levante'] = {
        ['name'] = 'Maserati Levante',
        ['brand'] = 'Maserati',
        ['model'] = 'levante',
        ['price'] = 112600,
        ['category'] = 'maserati',
        ['categoryLabel'] = 'Maserati',
        ['hash'] = `levante`,
        ['shop'] = 'luxury',
    },
    -- MAZDA
    ['84rx7k'] = {
        ['name'] = '1984 Mazda RX-7 Stanced Version',
        ['brand'] = 'Mazda',
        ['model'] = '84rx7k',
        ['price'] = 40000,
        ['category'] = 'mazda',
        ['categoryLabel'] = 'Mazda',
        ['hash'] = `84rx7k`,
        ['shop'] = 'pdm',
    },
    ['dragfd'] = {
        ['name'] = '2002 Mazda RX-7 FD Drag',
        ['brand'] = 'Mazda',
        ['model'] = 'dragfd',
        ['price'] = 84000,
        ['category'] = 'mazda',
        ['categoryLabel'] = 'Mazda',
        ['hash'] = `dragfd`,
        ['shop'] = 'pdm',
    },
    ['fc3s'] = {
        ['name'] = 'Mazda RX7 FC3S',
        ['brand'] = 'Mazda',
        ['model'] = 'fc3s',
        ['price'] = 45000,
        ['category'] = 'mazda',
        ['categoryLabel'] = 'Mazda',
        ['hash'] = `fc3s`,
        ['shop'] = 'pdm',
    },
    ['majfd'] = {
        ['name'] = 'Mazda RX-7 FD',
        ['brand'] = 'Mazda',
        ['model'] = 'majfd',
        ['price'] = 50000,
        ['category'] = 'mazda',
        ['categoryLabel'] = 'Mazda',
        ['hash'] = `majfd`,
        ['shop'] = 'pdm',
    },
    ['miata3'] = {
        ['name'] = '1989 Mazda Miata NA',
        ['brand'] = 'Mazda',
        ['model'] = 'miata3',
        ['price'] = 24000,
        ['category'] = 'mazda',
        ['categoryLabel'] = 'Mazda',
        ['hash'] = `miata3`,
        ['shop'] = 'pdm',
    },
    ['na6'] = {
        ['name'] = 'Mazda MX-5 Miata (NA6C)',
        ['brand'] = 'Mazda',
        ['model'] = 'na6',
        ['price'] = 35000,
        ['category'] = 'mazda',
        ['categoryLabel'] = 'Mazda',
        ['hash'] = `na6`,
        ['shop'] = 'pdm',
    },
    -- MCLAREN
    ['650s'] = {
        ['name'] = 'McLaren 650S Coupe',
        ['brand'] = 'McLaren',
        ['model'] = '650s',
        ['price'] = 10000,
        ['category'] = 'mclaren',
        ['categoryLabel'] = 'MCLAREN',
        ['hash'] = `650s`,
        ['shop'] = 'luxury',
    },
    ['675lt'] = {
        ['name'] = '2016 McLaren 675LT Coupe',
        ['brand'] = 'McLaren',
        ['model'] = '675lt',
        ['price'] = 10000,
        ['category'] = 'mclaren',
        ['categoryLabel'] = 'MCLAREN',
        ['hash'] = `675lt`,
        ['shop'] = 'luxury',
    },
    ['720s'] = {
        ['name'] = '2017 McLaren 720S',
        ['brand'] = 'McLaren',
        ['model'] = '720s',
        ['price'] = 10000,
        ['category'] = 'mclaren',
        ['categoryLabel'] = 'MCLAREN',
        ['hash'] = `720s`,
        ['shop'] = 'luxury',
    },
    ['gtr96'] = {
        ['name'] = '1996 McLaren F1 GTR',
        ['brand'] = 'McLaren',
        ['model'] = 'gtr96',
        ['price'] = 10000,
        ['category'] = 'mclaren',
        ['categoryLabel'] = 'MCLAREN',
        ['hash'] = `gtr96`,
        ['shop'] = 'luxury',
    },
    ['mcst'] = {
        ['name'] = '2020 McLaren Speedtail',
        ['brand'] = 'McLaren',
        ['model'] = 'mcst',
        ['price'] = 10000,
        ['category'] = 'mclaren',
        ['categoryLabel'] = 'MCLAREN',
        ['hash'] = `mcst`,
        ['shop'] = 'luxury',
    },
    ['mp412c'] = {
        ['name'] = 'McLaren MP4-12C',
        ['brand'] = 'McLaren',
        ['model'] = 'mp412c',
        ['price'] = 10000,
        ['category'] = 'mclaren',
        ['categoryLabel'] = 'MCLAREN',
        ['hash'] = `mp412c`,
        ['shop'] = 'luxury',
    },
    ['senna'] = {
        ['name'] = '2019 McLaren Senna',
        ['brand'] = 'McLaren',
        ['model'] = 'senna',
        ['price'] = 10000,
        ['category'] = 'mclaren',
        ['categoryLabel'] = 'MCLAREN',
        ['hash'] = `senna`,
        ['shop'] = 'luxury',
    },
    -- MERCEDES
    ['amggtrr20'] = {
        ['name'] = '2020 Mercedes-Benz AMG GT-R Roadster',
        ['brand'] = 'Mercedes-Benz',
        ['model'] = 'amggtrr20',
        ['price'] = 191745,
        ['category'] = 'mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = 'amggtrr20',
        ['shop'] = 'pdm',
    },
    ['c6320'] = {
        ['name'] = '2020 Mercedes-AMG C63s',
        ['brand'] = 'Mercedes-AMG',
        ['model'] = 'c6320',
        ['price'] = 76695,
        ['category'] = 'mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = 'c6320',
        ['shop'] = 'pdm',
    },
    ['G65'] = {
        ['name'] = '2013 Mercedes-Benz G65 AMG',
        ['brand'] = 'Mercedes-Benz',
        ['model'] = 'G65',
        ['price'] = 194500,
        ['category'] = 'mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = 'G65',
        ['shop'] = 'pdm',
    },
    ['e400'] = {
        ['name'] = '2019 Mercedes-Benz E400 Coupe 4matic (C238)',
        ['brand'] = 'Mercedes-Benz',
        ['model'] = 'e400',
        ['price'] = 43762,
        ['category'] = 'mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = 'e400',
        ['shop'] = 'pdm',
    },
    ['gl63'] = {
        ['name'] = 'Mercedes-Benz GL63 AMG',
        ['brand'] = 'Mercedes-Benz',
        ['model'] = 'gl63',
        ['price'] = 149115,
        ['category'] = 'mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = 'gl63',
        ['shop'] = 'pdm',
    },
    ['mbc63'] = {
        ['name'] = '2012 Mercedes-Benz C63 AMG Coupe Black Series',
        ['brand'] = 'Mercedes-Benz',
        ['model'] = 'mbc63',
        ['price'] = 182000,
        ['category'] = 'mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = 'mbc63',
        ['shop'] = 'pdm',
    },
    ['s500w222'] = {
        ['name'] = '2014 Mercedes-Benz S500 W222',
        ['brand'] = 'Mercedes-Benz',
        ['model'] = 's500w222',
        ['price'] = 94000,
        ['category'] = 'mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = 's500w222',
        ['shop'] = 'pdm',
    },
    ['sl500'] = {
        ['name'] = '1995 Mercedes-Benz SL500',
        ['brand'] = 'Mercedes-Benz',
        ['model'] = 'sl500',
        ['price'] = 37000,
        ['category'] = 'mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = 'sl500',
        ['shop'] = 'pdm',
    },
    ['v250'] = {
        ['name'] = 'Mercedes-Benz V-class 250 Bluetec LWB',
        ['brand'] = 'Mercedes-Benz',
        ['model'] = 'v250',
        ['price'] = 88110,
        ['category'] = 'mercedes',
        ['categoryLabel'] = 'Mercedes',
        ['hash'] = 'v250',
        ['shop'] = 'pdm',
    },
    -- MITSUBISHI
    ['cp9a'] = {
        ['name'] = 'Mitsubishi Lancer Evo VI T.M.E (CP9A)',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'cp9a',
        ['price'] = 19000,
        ['category'] = 'mitsubishi',
        ['categoryLabel'] = 'Mitsubishi',
        ['hash'] = 'cp9a',
        ['shop'] = 'pdm',
    },
    ['fto'] = {
        ['name'] = 'Mitsubishi FTO GP Version-R',
        ['brand'] = 'Mitsubishi',
        ['model'] = 'fto',
        ['price'] = 11118,
        ['category'] = 'mitsubishi',
        ['categoryLabel'] = 'Mitsubishi',
        ['hash'] = 'fto',
        ['shop'] = 'pdm',
    },
    -- NISSAN
    ['180sx'] = {
        ['name'] = 'Nissan 180SX Type-X',
        ['brand'] = 'Nissan',
        ['model'] = '180sx',
        ['price'] = 4184,
        ['category'] = 'nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `180sx`,
        ['shop'] = 'pdm',
    },
    ['gtr'] = {
        ['name'] = '2017 Nissan GTR',
        ['brand'] = 'Nissan',
        ['model'] = 'gtr',
        ['price'] = 111600,
        ['category'] = 'nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `gtr`,
        ['shop'] = 'pdm',
    },
    ['gtrc'] = {
        ['name'] = '2017 R35 Nissan GTR Convertible',
        ['brand'] = 'Nissan',
        ['model'] = 'gtrc',
        ['price'] = 141146,
        ['category'] = 'nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `gtrc`,
        ['shop'] = 'pdm',
    },
    ['maj350'] = {
        ['name'] = 'Nissan Fairlady Z Z33',
        ['brand'] = 'Nissan',
        ['model'] = 'maj350',
        ['price'] = 17764,
        ['category'] = 'nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `maj350`,
        ['shop'] = 'pdm',
    },
    ['nis15'] = {
        ['name'] = 'Nissan Silvia S15 Spec-R',
        ['brand'] = 'Nissan',
        ['model'] = 'nis15',
        ['price'] = 22563,
        ['category'] = 'nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `nis15`,
        ['shop'] = 'pdm',
    },
    ['nissantitan17'] = {
        ['name'] = '2017 Nissan Titan Warrior',
        ['brand'] = 'Nissan',
        ['model'] = 'nissantitan17',
        ['price'] = 44800,
        ['category'] = 'nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `nissantitan17`,
        ['shop'] = 'pdm',
    },
    ['ns350'] = {
        ['name'] = 'Nissan 350z Stardast',
        ['brand'] = 'Nissan',
        ['model'] = 'ns350',
        ['price'] = 4,
        ['category'] = 'nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `ns350`,
        ['shop'] = 'pdm',
    },
    ['nzp'] = {
        ['name'] = 'Nissan 370z "Pandem"',
        ['brand'] = 'Nissan',
        ['model'] = 'nzp',
        ['price'] = 30985,
        ['category'] = 'nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `nzp`,
        ['shop'] = 'pdm',
    },
    ['s14'] = {
        ['name'] = '1998 Nissan Silvia K',
        ['brand'] = 'Nissan',
        ['model'] = 's14',
        ['price'] = 17165,
        ['category'] = 'nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `s14`,
        ['shop'] = 'pdm',
    },
    ['Safari97'] = {
        ['name'] = '1997 Nissan Patrol Super Safari Y60',
        ['brand'] = 'Nissan',
        ['model'] = 'Safari97',
        ['price'] = 17372,
        ['category'] = 'nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `Safari97`,
        ['shop'] = 'pdm',
    },
    ['skyline'] = {
        ['name'] = 'Nissan Skyline GT-R (BNR34)',
        ['brand'] = 'Nissan',
        ['model'] = 'skyline',
        ['price'] = 70000,
        ['category'] = 'nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `skyline`,
        ['shop'] = 'pdm',
    },
    ['z32'] = {
        ['name'] = 'Nissan 300ZX Z32',
        ['brand'] = 'Nissan',
        ['model'] = 'z32',
        ['price'] = 48905,
        ['category'] = 'nissan',
        ['categoryLabel'] = 'Nissan',
        ['hash'] = `z32`,
        ['shop'] = 'pdm',
    },
    -- PORSCHE
    ['maj935'] = {
        ['name'] = '1978 Porsche 935 Moby Dick',
        ['brand'] = 'Porsche',
        ['model'] = 'maj935',
        ['price'] = 28270,
        ['category'] = 'porsche',
        ['categoryLabel'] = 'Porsche',
        ['hash'] = `maj935`,
        ['shop'] = 'luxury',
    },
    ['pcs18'] = {
        ['name'] = '2018 Porsche Cayenne S',
        ['brand'] = 'Porsche',
        ['model'] = 'pcs18',
        ['price'] = 78100,
        ['category'] = 'porsche',
        ['categoryLabel'] = 'Porsche',
        ['hash'] = `pcs18`,
        ['shop'] = 'luxury',
    },
    ['718caymans'] = {
        ['name'] = 'Porsche 718 Cayman S',
        ['brand'] = 'Porsche',
        ['model'] = '718caymans',
        ['price'] = 90700,
        ['category'] = 'porsche',
        ['categoryLabel'] = 'Porsche',
        ['hash'] = `718caymans`,
        ['shop'] = 'luxury',
    },
    ['cgt'] = {
        ['name'] = '2003 Porsche Carrera GT (980)',
        ['brand'] = 'Porsche',
        ['model'] = 'cgt',
        ['price'] = 1650000,
        ['category'] = 'porsche',
        ['categoryLabel'] = 'Porsche',
        ['hash'] = `cgt`,
        ['shop'] = 'luxury',
    },
    ['pm19'] = {
        ['name'] = '2019 Porsche Macan Turbo',
        ['brand'] = 'Porsche',
        ['model'] = 'pm19',
        ['price'] = 50950,
        ['category'] = 'porsche',
        ['categoryLabel'] = 'Porsche',
        ['hash'] = `pm19`,
        ['shop'] = 'luxury',
    },
    ['taycan'] = {
        ['name'] = '2020 Porsche Taycan Turbo S',
        ['brand'] = 'Porsche',
        ['model'] = 'taycan',
        ['price'] = 213900,
        ['category'] = 'porsche',
        ['categoryLabel'] = 'Porsche',
        ['hash'] = `taycan`,
        ['shop'] = 'luxury',
    }
    -- RANGEROVER
    ['rrevoque'] = {
        ['name'] = 'Range Rover Evoque',
        ['brand'] = 'Range Rover',
        ['model'] = 'rrevoque',
        ['price'] = 56900,
        ['category'] = 'rangerover',
        ['categoryLabel'] = 'Range Rover',
        ['hash'] = `rrevoque`,
        ['shop'] = 'pdm',
    },
    ['rrst'] = {
        ['name'] = 'Range Rover Vogue Startech',
        ['brand'] = 'Range Rover',
        ['model'] = 'rrst',
        ['price'] = 44955,
        ['category'] = 'rangerover',
        ['categoryLabel'] = 'Range Rover',
        ['hash'] = `rrst`,
        ['shop'] = 'pdm',
    },
    ['rsvr16'] = {
        ['name'] = '2016 Range Rover Sport SVR',
        ['brand'] = 'Range Rover',
        ['model'] = 'rsvr16',
        ['price'] = 58922,
        ['category'] = 'rangerover',
        ['categoryLabel'] = 'Range Rover',
        ['hash'] = `rsvr16`,
        ['shop'] = 'pdm',
    },
    -- ROLLSROYCE
    ['dawnonyx'] = {
        ['name'] = '2016 Rolls-Royce Dawn Onyx',
        ['brand'] = 'Rolls Royce',
        ['model'] = 'dawnonyx',
        ['price'] = 378000,
        ['category'] = 'rollsroyce',
        ['categoryLabel'] = 'Rolls Royce',
        ['hash'] = `dawnonyx`,
        ['shop'] = 'luxury',
    },
    
    ['wraith'] = {
        ['name'] = 'Rolls-Royce Wraith',
        ['brand'] = 'Rolls Royce',
        ['model'] = 'wraith',
        ['price'] = 344500,
        ['category'] = 'rollsroyce',
        ['categoryLabel'] = 'Rolls Royce',
        ['hash'] = `wraith`,
        ['shop'] = 'luxury',
    },
    
    ['rculi'] = {
        ['name'] = 'Rolls Royce Cullinan',
        ['brand'] = 'Rolls Royce',
        ['model'] = 'rculi',
        ['price'] = 355000,
        ['category'] = 'rollsroyce',
        ['categoryLabel'] = 'Rolls Royce',
        ['hash'] = `rculi`,
        ['shop'] = 'luxury',
    },
    
    ['rrphantom'] = {
        ['name'] = '2018 Rolls-Royce Phantom VIII',
        ['brand'] = 'Rolls Royce',
        ['model'] = 'rrphantom',
        ['price'] = 420000,
        ['category'] = 'rollsroyce',
        ['categoryLabel'] = 'Rolls Royce',
        ['hash'] = `rrphantom`,
        ['shop'] = 'luxury',
    },
    -- SUBARU
    ['subisti08'] = {
        ['name'] = '2008 Subaru WRX STi',
        ['brand'] = 'Subaru',
        ['model'] = 'subisti08',
        ['price'] = 44995,
        ['category'] = 'subaru',
        ['categoryLabel'] = 'Subaru',
        ['hash'] = 'subisti08',
        ['shop'] = 'pdm',
    },
    ['subwrx'] = {
        ['name'] = '2004 Subaru Impreza WRX STI',
        ['brand'] = 'Subaru',
        ['model'] = 'subwrx',
        ['price'] = 31120,
        ['category'] = 'subaru',
        ['categoryLabel'] = 'Subaru',
        ['hash'] = 'subwrx',
        ['shop'] = 'pdm',
    },
    ['svx'] = {
        ['name'] = '1996 Subaru Alcyone SVX',
        ['brand'] = 'Subaru',
        ['model'] = 'svx',
        ['price'] = 11500,
        ['category'] = 'subaru',
        ['categoryLabel'] = 'Subaru',
        ['hash'] = 'svx',
        ['shop'] = 'pdm',
    },
    -- SUZUKI
    ['gsxr19'] = {
        ['name'] = '2019 Suzuki GSX-R1000R',
        ['brand'] = 'Suzuki',
        ['model'] = 'gsxr19',
        ['price'] = 17499,
        ['category'] = 'suzuki',
        ['categoryLabel'] = 'Suzuki',
        ['hash'] = 'gsxr19',
        ['shop'] = 'pdm',
    },
    ['katana'] = {
        ['name'] = '2019 Suzuki Katana',
        ['brand'] = 'Suzuki',
        ['model'] = 'katana',
        ['price'] = 13500,
        ['category'] = 'suzuki',
        ['categoryLabel'] = 'Suzuki',
        ['hash'] = 'katana',
        ['shop'] = 'pdm',
    },    
    -- TESLA
    ['tr22'] = {
        ['name'] = '2020 Tesla Roadster',
        ['brand'] = 'Tesla',
        ['model'] = 'tr22',
        ['price'] = 200000,
        ['category'] = 'tesla',
        ['categoryLabel'] = 'Tesla',
        ['hash'] = `tr22`,
        ['shop'] = 'pdm',
    },
    ['p90d'] = {
        ['name'] = 'Tesla Model X P90D',
        ['brand'] = 'Tesla',
        ['model'] = 'p90d',
        ['price'] = 133700,
        ['category'] = 'tesla',
        ['categoryLabel'] = 'Tesla',
        ['hash'] = `p90d`,
        ['shop'] = 'pdm',
    },
    ['models'] = {
        ['name'] = '2016 Tesla Model S P90D',
        ['brand'] = 'Tesla',
        ['model'] = 'models',
        ['price'] = 109500,
        ['category'] = 'tesla',
        ['categoryLabel'] = 'Tesla',
        ['hash'] = `models`,
        ['shop'] = 'pdm',
    },
    ['tmodel'] = {
        ['name'] = '2018 Tesla Model 3',
        ['brand'] = 'Tesla',
        ['model'] = 'tmodel',
        ['price'] = 38700,
        ['category'] = 'tesla',
        ['categoryLabel'] = 'Tesla',
        ['hash'] = `tmodel`,
        ['shop'] = 'pdm',
    },
    ['teslax'] = {
        ['name'] = '2016 Tesla Model X P90D',
        ['brand'] = 'Tesla',
        ['model'] = 'teslax',
        ['price'] = 10000,
        ['category'] = 'tesla',
        ['categoryLabel'] = 'Tesla',
        ['hash'] = `teslax`,
        ['shop'] = 'pdm',
    },
    ['teslapd'] = {
        ['name'] = '2017 Tesla Model S Prior design',
        ['brand'] = 'Tesla',
        ['model'] = 'teslapd',
        ['price'] = 116700,
        ['category'] = 'tesla',
        ['categoryLabel'] = 'Tesla',
        ['hash'] = `teslapd`,
        ['shop'] = 'pdm',
    },
    -- TOYOTA
    ['cam8tun'] = {
        ['name'] = '2018 Toyota Camry XSE',
        ['brand'] = 'Toyota',
        ['model'] = 'cam8tun',
        ['price'] = 25990,
        ['category'] = 'toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `cam8tun`,
        ['shop'] = 'pdm',
    },
    ['vxr'] = {
        ['name'] = '2016 Toyota Land Cruiser VXR',
        ['brand'] = 'Toyota',
        ['model'] = 'vxr',
        ['price'] = 85000,
        ['category'] = 'toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `vxr`,
        ['shop'] = 'pdm',
    },
    ['toysupmk4'] = {
        ['name'] = '1998 Toyota Supra Turbo (A80)',
        ['brand'] = 'Toyota',
        ['model'] = 'toysupmk4',
        ['price'] = 187000,
        ['category'] = 'toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `toysupmk4`,
        ['shop'] = 'pdm',
    },
    ['mk2100'] = {
        ['name'] = 'Toyota Mark II JZX100',
        ['brand'] = 'Toyota',
        ['model'] = 'mk2100',
        ['price'] = 36552,
        ['category'] = 'toyota',
        ['categoryLabel'] = 'Toyota',
        ['hash'] = `mk2100`,
        ['shop'] = 'pdm',
    },    
    -- VOLKSWAGEN
    ['golfgti7'] = {
        ['name'] = '2015 Volkswagen Golf GTI MK7',
        ['brand'] = 'Volkswagen',
        ['model'] = 'golfgti7',
        ['price'] = 21153,
        ['category'] = 'volkswagen',
        ['categoryLabel'] = 'Volkswagen',
        ['hash'] = `golfgti7`,
        ['shop'] = 'pdm',
    },
    -- VOLVO
    ['xc90'] = {
        ['name'] = 'Volvo XC90 T8',
        ['brand'] = 'Volvo',
        ['model'] = 'xc90',
        ['price'] = 57095,
        ['category'] = 'volvo',
        ['categoryLabel'] = 'Volvo',
        ['hash'] = `xc90`,
        ['shop'] = 'pdm',
    },
    -- #END OF PLOKS FOR QB##--
    ['Urus_Stretch_6'] = {
        ['name'] = 'Urus Strech',
        ['brand'] = 'Lambo',
        ['model'] = 'Urus_Stretch_6',
        ['price'] = 5967400,
        ['category'] = 'custom',
        ['categoryLabel'] = 'Custom',
        ['hash'] = `Urus_Stretch_6`,
        ['shop'] = 'luxury',
    },
    ['hover_bike'] = {
        ['name'] = 'Hover Bike',
        ['brand'] = 'Hover',
        ['model'] = 'hover_bike',
        ['price'] = 60000000,
        ['category'] = 'custom',
        ['categoryLabel'] = 'Custom',
        ['hash'] = `hover_bike`,
        ['shop'] = 'luxury',
    },
